# ansible-playbook ./cpm_config_backup.yml
- name: Get Device Parameters
  hosts: all
#  collections:
#    - wti.remote
  connection: local
  gather_facts: false

  tasks:
#    - set_fact:  wti.remote.use_https=False
#      when:  wti.remote.use_https is undefined
#    - set_fact:  wti.remote.validate_certs=False
#      when:  wti.remote.validate_certs is undefined

    - name: Run Backup Unit Config
      wti.remote.cpm_config_backup:
        cpm_url: "{{ansible_host}}"
        cpm_username: "{{ansible_user}}"
        cpm_password: "{{ansible_pw}}"
        use_https: "{{use_https}}"
        validate_certs: "{{validate_certs}}"

#      register: testout
#    - name: dump test output
#      debug:
#        msg: "{{ testout['data'] }}"
