# ansible-playbook ./cpm_config_backup.yml
- name: Get Device Parameters
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Run Backup Device Parameters
      wti.remote.cpm_config_backup:
        cpm_url: "{{ ansible_host }}"
        cpm_username: "{{ ansible_user }}"
        cpm_password: "{{ ansible_pw }}"
        use_https: "{{ use_https }}"
        validate_certs: "{{ validate_certs }}"
      register: testout

    - name: Dump test output
      ansible.builtin.debug:
        msg: "{{ testout['data'] }}"
