# ansible-playbook ./temp_info.yml -e ansible_hosts=yourhostname
- name: Get Temperature information from WTI device
  hosts: "{{ ansible_hosts }}"
  collections:
    - wti.remote
  connection: local
  gather_facts: false

  tasks:
    - name: Get temperature info
      wti.remote.cpm_temp_info:
        cpm_url: "{{ ansible_host }}"
        cpm_username: "{{ ansible_user }}"
        cpm_password: "{{ ansible_pw }}"
        use_https: "{{ use_https | default(true) }}"
        validate_certs: "{{ validate_certs | default(true) }}"
      register: testout

    - name: Display Temperature Info
      debug:
        msg:
          temperature: "{{ testout.data.temperature }} {{ testout.data.format }}"
          timestamp: "{{ testout.data.timestamp }}"
