# ansible-playbook ./ssh_config.yml -e ansible_hosts=youransibledefinedhostnames
- name: Set SSH Parameters
  hosts: "{{ansible_hosts}}"  # pass as -e ansible_hosts=wti_demo on the commandline
  collections:
     - wti.remote
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - cpm_ssh_config:
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"
      ssh_enable: "{{ssh_enable}}"
      ssh_port:  "{{ssh_port}}"
      ssh_level:  "{{ssh_level}}"
      ssh_viewenable: "{{ssh_viewenable}}"
      ssh_viewbidirect: "{{ssh_viewbidirect}}"
      ssh_allowpseudo: "{{ssh_allowpseudo}}"
      ssh_disablepassauth: "{{ssh_disablepassauth}}"
      ssh_disablechacha20: "{{ssh_disablechacha20}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
